version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: lab-4.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lab_db
    ports:
      - "0.0.0.0:5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: